name: React CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener el código del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias del Frontend
        working-directory: ./client
        run: npm install

      - name: Ejecutar UI Tests (Vitest)
        working-directory: ./client
        run: npm run test

      - name: Construir la aplicación para producción (Build)
        working-directory: ./client
        run: npm run build