name: React CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Obtain source code
        uses: actions/checkout@v4

      - name: Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install frontend dependencies
        working-directory: ./client
        run: npm install

      - name: Execute tests (Vitest)
        working-directory: ./client
        run: npm run test

      - name: Build app in production (Build)
        working-directory: ./client
        run: npm run build